name: Laravel CI-CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Bu test uchun
        run: echo "Test uchun"

      - name: Kodni GitHub repositorydan olib kelish
        uses: actions/checkout@v3

      # - name: PHP versiyasini sozlash (8.2)
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: '8.2'

      - name: Serverga deploy qilish
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
          
            cd /var/www/new_project/
            git pull origin main
            composer install --no-dev --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:clear
            php artisan queue:restart
            sudo systemctl restart nginx
